items/urls.py
from django.urls import path

from items.views import items_list, get_item

app_name = 'items'

urlpatterns = [
    path('', items_list, name='items'),
    path('<int:item_id>/', get_item, name='item'),
]

shop/urls.py
from django.contrib import admin
from django.urls import path, include

from items.views import buy, thanks, index, add_order, order, confirm_order

urlpatterns = [
    path('admin/', admin.site.urls),
    path('item/', include('items.urls')),
    path('', index, name='index'),
    path('thanks/', thanks, name='thanks'),
    path('buy/<int:item_id>/', buy, name='buy'),
    path('add_order/', add_order, name='add_order'),
    path('order/', order, name='order'),
    path('confirm_order/', confirm_order, name='confirm_order'),
]

items/models.py
from django.db import models


class Item(models.Model):
    name = models.CharField(verbose_name='Наименование', max_length=100)
    description = models.TextField(verbose_name='Описание')
    price = models.ForeignKey('Price', on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class Price(models.Model):
    price = models.PositiveIntegerField(verbose_name='Цена')
    stripe_price_id = models.CharField(verbose_name='ID цены товара в базе stripe', max_length=100)

    def __str__(self):
        return self.stripe_price_id


class Order(models.Model):
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(verbose_name='Количество')

    @property
    def total_cost(self):
        return self.item.price.price * self.quantity

items/views.py
import json
import stripe
from django.conf import settings
from django.http import JsonResponse
from django.shortcuts import render
from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt
from items.models import Item, Price, Order

stripe.api_key = settings.STRIPE_SECRET_KEY


def items_list(request):
    template = 'items/items.html'
    items = Item.objects.all()
    context = {'items': items}
    return render(request, template, context)


def get_item(request, item_id):
    template = 'items/item.html'
    item = Item.objects.get(id=item_id)
    price = Price.objects.get(item=item.id)
    context = {
        'item': item,
        'price': price,
    }
    return render(request, template, context)


def order(request):
    template = 'items/order.html'
    order = Order.objects.all()
    item = Item.objects.all()
    context = {'order': order, 'item': item}
    return render(request, template, context)


def index(request):
    return render(request, 'items/index.html')


def thanks(request):
    return render(request, 'items/thanks.html')


@csrf_exempt
def buy(request, item_id, quantity=1):
    quantity = json.loads(request.body)
    item = Item.objects.get(id=item_id)
    price = Price.objects.get(item=item.id)
    session = stripe.checkout.Session.create(
        payment_method_types=['card'],
        line_items=[{
            'price': price.stripe_price_id,
            'quantity': quantity,
        }],
        mode='payment',
        success_url=request.build_absolute_uri(reverse('thanks')),
        cancel_url=request.build_absolute_uri(reverse('index')),
    )

    return JsonResponse({
        'session_id': session.id,
        'stripe_public_key': settings.STRIPE_PUBLIC_KEY
    })


@csrf_exempt
def confirm_order(request):
    order = Order.objects.all().values()
    line_items = [{'price': Price.objects.get(item=position['item_id']),
                   'quantity': position['quantity']} for position in order]
    session = stripe.checkout.Session.create(
        payment_method_types=['card'],
        line_items=line_items,
        mode='payment',
        success_url=request.build_absolute_uri(reverse('thanks')),
        cancel_url=request.build_absolute_uri(reverse('index')),
    )

    return JsonResponse({
        'session_id': session.id,
        'stripe_public_key': settings.STRIPE_PUBLIC_KEY
    })


def add_order(request):
    product_id = int(request.GET.get('product_id'))
    quantity = int(request.GET.get('quantity'))
    if Item.objects.get(id=product_id):
        Order.objects.create(item_id=product_id, quantity=quantity)
        return JsonResponse({'status': 'Added to order'})
    else:
        return JsonResponse({'status': 'Error'})

items/templates/items/index.html
{% load static %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>Shop</title>

    <link href="{% static 'bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'narrow-jumbotron.css' %}" rel="stylesheet">

  </head>

  <body>


    <div class="container">
      <div class="header clearfix">
        <nav>
          <ul class="nav nav-pills float-right">
            <li class="nav-item" style="display: flex;">
              <a class="nav-link active" href="/item/" style="margin: 0 10px;">Items</a>
              <a class="nav-link active" href="/order/"  style="margin: 0 10px;">My order</a>
            </li>
          </ul>
        </nav>
        <h3 class="text-muted">Shop</h3>
      </div>

      {% block content %}
      {% endblock %}


      <footer class="footer">
        <p>&copy; Shop MegaMarket 2022</p>
      </footer>
    </div>
  </body>
</html>

items/templates/items/item.html
{% extends 'items/index.html' %}
{% load static %}



{% block content %}

    <div class="jumbotron">
      <input type="hidden" value="{{item.id}}" class="item_id">
      <h1 class="display-3">{{ item.name }}</h1>
      <p class="desc"> {{ item.description }} </p>
      <p class="lead">Price {{ price.price }} р.</p>
      <p class="quantity">Quantity: </p>
      <form name="quantity">
        <input type="number" class="qty-input" id="quantity" value="1"  min="1"/>
      </form>
      <button id="buy-button" class="btn btn-primary">Buy</button>
      <button id="add_order-button" class="btn btn-primary addToOrderBtn">Add Order</button>
    </div>

    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
    <script src="//cdn.jsdelivr.net/npm/alertifyjs@1.13.1/build/alertify.min.js"></script>
    <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/alertifyjs@1.13.1/build/css/alertify.min.css"/>
    <script src="{% static 'custom.js' %}"></script>
    <script src="https://js.stripe.com/v3/"></script>


    <script>


      const buy_now_button = document.querySelector('#buy-button')
      buy_now_button.addEventListener('click', event => {
        let quantity = document.getElementById("quantity").value;
        if( !(quantity > 0)) {
          quantity = 1;
        }
        fetch('/buy/{{item.id}}/', {method: 'POST', body: quantity})
        .then((result) => { return result.json() })
        .then((data) => {
          var stripe = Stripe(data.stripe_public_key);

          stripe.redirectToCheckout({sessionId: data.session_id})
          .then(function (result) {
          });
        })
      })


    </script>


{% endblock %}

items/templates/items/items.html
{% extends 'items/index.html' %}

{% block content %}
    <div class="items">
        {% for item in items %}
        <li>
            <a href="{% url 'items:item' item.id %}">{{ item.name }}</a>
        </li>
        {% empty %}
        <li>No items</li>
        {% endfor %}
    </div>
{% endblock %}

items/templates/items/order.html
{% extends 'items/index.html' %}
{% load static %}
{% block content %}

    <div class="jumbotron">
      <h3 class="text-muted">Order list:</h3>
      <div class="orders">
        {% for position in order %}
        <li class="my-row" style="  display:flex;">
            <p class="desc"> Item: {{ position.item }} Quantity: {{ position.quantity }}
            Total cost: {{ position.total_cost }}</p>
            {% empty %}
        <li>No orders</li>
          {% endfor %}
        </li>
      </div>
      <button id="confirm-order" class="btn btn-primary">Confirm order</button>
    </div>

    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
    <script src="//cdn.jsdelivr.net/npm/alertifyjs@1.13.1/build/alertify.min.js"></script>
    <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/alertifyjs@1.13.1/build/css/alertify.min.css"/>
    <script src="{% static 'custom.js' %}"></script>
    <script src="https://js.stripe.com/v3/"></script>


    <script>


      const confirm_order = document.querySelector('#confirm-order')
      confirm_order.addEventListener('click', event => {
        fetch('/confirm_order/', {method: 'GET'})
        .then((result) => { return result.json() })
        .then((data) => {
          var stripe = Stripe(data.stripe_public_key);

          stripe.redirectToCheckout({sessionId: data.session_id})
          .then(function (result) {
          });
        })
      })


    </script>

{% endblock %}

items/templates/items/thanks.html
{% extends 'items/index.html' %}

{% block content %}
      <div class="jumbotron">
        <h1 class="display-3">Thanks for buying</h1>
      </div>

{% endblock %}